/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertPrefs = IDL.Record({
  'borrowRateThreshold' : IDL.Float64,
  'ltvThreshold' : IDL.Float64,
});
export const Time = IDL.Int;
export const EstatePlan = IDL.Record({
  'heirsCount' : IDL.Nat,
  'estateValue' : IDL.Float64,
  'timestamp' : Time,
  'distributionStrategy' : IDL.Text,
});
export const LeverageScenario = IDL.Record({
  'borrowRate' : IDL.Float64,
  'portfolioValue' : IDL.Float64,
  'targetYield' : IDL.Float64,
  'horizonYears' : IDL.Float64,
  'ltvRatio' : IDL.Float64,
  'timestamp' : Time,
  'assetType' : IDL.Text,
  'borrowAmount' : IDL.Float64,
});
export const TaxCalculation = IDL.Record({
  'ltcg' : IDL.Float64,
  'stcg' : IDL.Float64,
  'interestDeduction' : IDL.Float64,
});
export const UserData = IDL.Record({
  'leverageScenarios' : IDL.Vec(LeverageScenario),
  'estatePlans' : IDL.Vec(EstatePlan),
  'taxCalculations' : IDL.Vec(TaxCalculation),
  'alertPrefs' : IDL.Opt(AlertPrefs),
});

export const idlService = IDL.Service({
  'calculateLeverageMetrics' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [
        IDL.Record({
          'netSpread' : IDL.Float64,
          'marginCallTrigger' : IDL.Float64,
          'verdict' : IDL.Text,
          'effectiveReturn' : IDL.Float64,
          'riskScore' : IDL.Float64,
        }),
      ],
      [],
    ),
  'getAlertPrefs' : IDL.Func([], [IDL.Opt(AlertPrefs)], ['query']),
  'getEstatePlans' : IDL.Func([], [IDL.Vec(EstatePlan)], ['query']),
  'getLeverageScenarios' : IDL.Func([], [IDL.Vec(LeverageScenario)], ['query']),
  'getTaxCalculations' : IDL.Func([], [IDL.Vec(TaxCalculation)], ['query']),
  'getUserData' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
  'saveEstatePlan' : IDL.Func([EstatePlan], [], []),
  'saveLeverageScenario' : IDL.Func([LeverageScenario], [], []),
  'saveTaxCalculation' : IDL.Func([TaxCalculation], [], []),
  'setAlertPrefs' : IDL.Func([AlertPrefs], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertPrefs = IDL.Record({
    'borrowRateThreshold' : IDL.Float64,
    'ltvThreshold' : IDL.Float64,
  });
  const Time = IDL.Int;
  const EstatePlan = IDL.Record({
    'heirsCount' : IDL.Nat,
    'estateValue' : IDL.Float64,
    'timestamp' : Time,
    'distributionStrategy' : IDL.Text,
  });
  const LeverageScenario = IDL.Record({
    'borrowRate' : IDL.Float64,
    'portfolioValue' : IDL.Float64,
    'targetYield' : IDL.Float64,
    'horizonYears' : IDL.Float64,
    'ltvRatio' : IDL.Float64,
    'timestamp' : Time,
    'assetType' : IDL.Text,
    'borrowAmount' : IDL.Float64,
  });
  const TaxCalculation = IDL.Record({
    'ltcg' : IDL.Float64,
    'stcg' : IDL.Float64,
    'interestDeduction' : IDL.Float64,
  });
  const UserData = IDL.Record({
    'leverageScenarios' : IDL.Vec(LeverageScenario),
    'estatePlans' : IDL.Vec(EstatePlan),
    'taxCalculations' : IDL.Vec(TaxCalculation),
    'alertPrefs' : IDL.Opt(AlertPrefs),
  });
  
  return IDL.Service({
    'calculateLeverageMetrics' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [
          IDL.Record({
            'netSpread' : IDL.Float64,
            'marginCallTrigger' : IDL.Float64,
            'verdict' : IDL.Text,
            'effectiveReturn' : IDL.Float64,
            'riskScore' : IDL.Float64,
          }),
        ],
        [],
      ),
    'getAlertPrefs' : IDL.Func([], [IDL.Opt(AlertPrefs)], ['query']),
    'getEstatePlans' : IDL.Func([], [IDL.Vec(EstatePlan)], ['query']),
    'getLeverageScenarios' : IDL.Func(
        [],
        [IDL.Vec(LeverageScenario)],
        ['query'],
      ),
    'getTaxCalculations' : IDL.Func([], [IDL.Vec(TaxCalculation)], ['query']),
    'getUserData' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
    'saveEstatePlan' : IDL.Func([EstatePlan], [], []),
    'saveLeverageScenario' : IDL.Func([LeverageScenario], [], []),
    'saveTaxCalculation' : IDL.Func([TaxCalculation], [], []),
    'setAlertPrefs' : IDL.Func([AlertPrefs], [], []),
  });
};

export const init = ({ IDL }) => { return []; };