/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertPrefs {
  'borrowRateThreshold' : number,
  'ltvThreshold' : number,
}
export interface EstatePlan {
  'heirsCount' : bigint,
  'estateValue' : number,
  'timestamp' : Time,
  'distributionStrategy' : string,
}
export interface LeverageScenario {
  'borrowRate' : number,
  'portfolioValue' : number,
  'targetYield' : number,
  'horizonYears' : number,
  'ltvRatio' : number,
  'timestamp' : Time,
  'assetType' : string,
  'borrowAmount' : number,
}
export interface TaxCalculation {
  'ltcg' : number,
  'stcg' : number,
  'interestDeduction' : number,
}
export type Time = bigint;
export interface UserData {
  'leverageScenarios' : Array<LeverageScenario>,
  'estatePlans' : Array<EstatePlan>,
  'taxCalculations' : Array<TaxCalculation>,
  'alertPrefs' : [] | [AlertPrefs],
}
export interface _SERVICE {
  'calculateLeverageMetrics' : ActorMethod<
    [number, number, number, number],
    {
      'netSpread' : number,
      'marginCallTrigger' : number,
      'verdict' : string,
      'effectiveReturn' : number,
      'riskScore' : number,
    }
  >,
  'getAlertPrefs' : ActorMethod<[], [] | [AlertPrefs]>,
  'getEstatePlans' : ActorMethod<[], Array<EstatePlan>>,
  'getLeverageScenarios' : ActorMethod<[], Array<LeverageScenario>>,
  'getTaxCalculations' : ActorMethod<[], Array<TaxCalculation>>,
  'getUserData' : ActorMethod<[], [] | [UserData]>,
  'saveEstatePlan' : ActorMethod<[EstatePlan], undefined>,
  'saveLeverageScenario' : ActorMethod<[LeverageScenario], undefined>,
  'saveTaxCalculation' : ActorMethod<[TaxCalculation], undefined>,
  'setAlertPrefs' : ActorMethod<[AlertPrefs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];