/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaxCalculation {
    ltcg: number;
    stcg: number;
    interestDeduction: number;
}
export interface EstatePlan {
    heirsCount: bigint;
    estateValue: number;
    timestamp: Time;
    distributionStrategy: string;
}
export type Time = bigint;
export interface LeverageScenario {
    borrowRate: number;
    portfolioValue: number;
    targetYield: number;
    horizonYears: number;
    ltvRatio: number;
    timestamp: Time;
    assetType: string;
    borrowAmount: number;
}
export interface UserData {
    leverageScenarios: Array<LeverageScenario>;
    estatePlans: Array<EstatePlan>;
    taxCalculations: Array<TaxCalculation>;
    alertPrefs?: AlertPrefs;
}
export interface AlertPrefs {
    borrowRateThreshold: number;
    ltvThreshold: number;
}
export interface backendInterface {
    calculateLeverageMetrics(borrowAmount: number, borrowRate: number, targetYield: number, ltvRatio: number): Promise<{
        netSpread: number;
        marginCallTrigger: number;
        verdict: string;
        effectiveReturn: number;
        riskScore: number;
    }>;
    getAlertPrefs(): Promise<AlertPrefs | null>;
    getEstatePlans(): Promise<Array<EstatePlan>>;
    getLeverageScenarios(): Promise<Array<LeverageScenario>>;
    getTaxCalculations(): Promise<Array<TaxCalculation>>;
    getUserData(): Promise<UserData | null>;
    saveEstatePlan(plan: EstatePlan): Promise<void>;
    saveLeverageScenario(scenario: LeverageScenario): Promise<void>;
    saveTaxCalculation(tax: TaxCalculation): Promise<void>;
    setAlertPrefs(prefs: AlertPrefs): Promise<void>;
}
import type { AlertPrefs as _AlertPrefs, EstatePlan as _EstatePlan, LeverageScenario as _LeverageScenario, TaxCalculation as _TaxCalculation, UserData as _UserData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateLeverageMetrics(arg0: number, arg1: number, arg2: number, arg3: number): Promise<{
        netSpread: number;
        marginCallTrigger: number;
        verdict: string;
        effectiveReturn: number;
        riskScore: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateLeverageMetrics(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateLeverageMetrics(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAlertPrefs(): Promise<AlertPrefs | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertPrefs();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertPrefs();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEstatePlans(): Promise<Array<EstatePlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEstatePlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEstatePlans();
            return result;
        }
    }
    async getLeverageScenarios(): Promise<Array<LeverageScenario>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeverageScenarios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeverageScenarios();
            return result;
        }
    }
    async getTaxCalculations(): Promise<Array<TaxCalculation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxCalculations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxCalculations();
            return result;
        }
    }
    async getUserData(): Promise<UserData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserData();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserData();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveEstatePlan(arg0: EstatePlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEstatePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEstatePlan(arg0);
            return result;
        }
    }
    async saveLeverageScenario(arg0: LeverageScenario): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLeverageScenario(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLeverageScenario(arg0);
            return result;
        }
    }
    async saveTaxCalculation(arg0: TaxCalculation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTaxCalculation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTaxCalculation(arg0);
            return result;
        }
    }
    async setAlertPrefs(arg0: AlertPrefs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAlertPrefs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAlertPrefs(arg0);
            return result;
        }
    }
}
function from_candid_UserData_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserData): UserData {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AlertPrefs]): AlertPrefs | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserData]): UserData | null {
    return value.length === 0 ? null : from_candid_UserData_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leverageScenarios: Array<_LeverageScenario>;
    estatePlans: Array<_EstatePlan>;
    taxCalculations: Array<_TaxCalculation>;
    alertPrefs: [] | [_AlertPrefs];
}): {
    leverageScenarios: Array<LeverageScenario>;
    estatePlans: Array<EstatePlan>;
    taxCalculations: Array<TaxCalculation>;
    alertPrefs?: AlertPrefs;
} {
    return {
        leverageScenarios: value.leverageScenarios,
        estatePlans: value.estatePlans,
        taxCalculations: value.taxCalculations,
        alertPrefs: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.alertPrefs))
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
